// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYK9eE4toNIiWq3Iz0UAWYjDhGTXBus88',
    appId: '1:690841431941:web:d25622b161d2a52c9a9eec',
    messagingSenderId: '690841431941',
    projectId: 'meat-tracker-ce8f3',
    authDomain: 'meat-tracker-ce8f3.firebaseapp.com',
    storageBucket: 'meat-tracker-ce8f3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARlhny_uMOmAhICWAbaaeks0OAdlf5giI',
    appId: '1:690841431941:android:50a7a1cb9d12c12a9a9eec',
    messagingSenderId: '690841431941',
    projectId: 'meat-tracker-ce8f3',
    storageBucket: 'meat-tracker-ce8f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfT6_FSUoifgTgrlDAicjHWVjQt1DN9TE',
    appId: '1:690841431941:ios:49bf44a6517fd3509a9eec',
    messagingSenderId: '690841431941',
    projectId: 'meat-tracker-ce8f3',
    storageBucket: 'meat-tracker-ce8f3.appspot.com',
    iosClientId: '690841431941-mg2ru5tj40fpj1581t5b1arv5g9gp35b.apps.googleusercontent.com',
    iosBundleId: 'com.example.reducingMeatConsumptionApp',
  );
}
