// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMaTp6Y3faO-X3hiCxTB3yNi5flyh6cSY',
    appId: '1:1000083641743:web:3d1906c64ee6b3515ba7fa',
    messagingSenderId: '1000083641743',
    projectId: 'meat-tracker-790af',
    authDomain: 'meat-tracker-790af.firebaseapp.com',
    storageBucket: 'meat-tracker-790af.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtuGHLBoezPdaocjgvOUfszImsOR0PxyA',
    appId: '1:1000083641743:android:c2eb7675919d9ce45ba7fa',
    messagingSenderId: '1000083641743',
    projectId: 'meat-tracker-790af',
    storageBucket: 'meat-tracker-790af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEuCvSzeRaZNf78bFkOMStlPrOU7xBI-s',
    appId: '1:1000083641743:ios:e95cc2ea44affbdf5ba7fa',
    messagingSenderId: '1000083641743',
    projectId: 'meat-tracker-790af',
    storageBucket: 'meat-tracker-790af.appspot.com',
    iosClientId: '1000083641743-4c8u1n46d0v210v42em6m912376a6mfv.apps.googleusercontent.com',
    iosBundleId: 'com.example.reducingMeatConsumptionApp',
  );
}
